[phases.setup]
nixPkgs = ["nodejs_22", "python311"]

[phases.install]
cmds = [
  "cd frontend && npm install",
  "cd backend && npm install",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && npm start"