[phases.setup]
nixPkgs = [
  "nodejs_18",
  "python311"
]


[phases.install]
cmds = [
  "npm install",
  "cd frontend && npm install",
  "cd backend && npm install",
  "python -m pip install --upgrade pip",
  "python -m pip install -r backend/requirements.txt"
]


[phases.build]
cmds = [
  "cd frontend && npm run build"
]


[start]
cmd = "cd backend && npm start"